%YAML:1.0
---
Size: [ 960, 600 ]
K_LEFT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 368.8685, 0., 501.44,
           0., 368.8245, 288.105,
           0., 0., 1. ]
D_LEFT: !!opencv-matrix
   rows: 1
   cols: 8
   dt: d
   #[k1, k2, k3, k4, k5, k6, p1, p2]
   data: [ 0.166827, -0.0474667, -0.0971949, 0.158073, 0.0284703, -0.128941, -0.00038715, -3.54651e-05]
K_RIGHT: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 369.6055, 0., 486.8415,
           0., 369.5, 316.0995,
           0., 0., 1. ]
D_RIGHT: !!opencv-matrix
   rows: 1
   cols: 8
   dt: d
   #[k1, k2, k3, k4, k5, k6, p1, p2]
   data: [ 5.04115, 4.99752, 1.09963, 5.0549, 4.98573, 1.5555, -0.000501104, -8.76689e-05]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1, 0, 0, 
           0, 1, 0, 
           0, 0, 1 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0, 0, 0 ]
