sensing:
  zedx:
    left_image:
      undistorted: "/aiformula_sensing/zed_node/left_image/undistorted"
    right_image:
      undistorted: "/aiformula_sensing/zed_node/right_image/undistorted"
    imu: "/aiformula_sensing/zed_node/imu"
  input_can_data: "/aiformula_sensing/vehicle_info"
  vectornav:
    imu: "/aiformula_sensing/vectornav/imu"
    gnss: "/aiformula_sensing/vectornav/gnss"
  odometry:
    gyro: "/aiformula_sensing/gyro_odometry_publisher/odom"
    wheel: "/aiformula_sensing/wheel_odometry_publisher/odom"
    gnss: "/aiformula_sensing/gnss_odometry_publisher/odom"
  rear_potentiometer: "/aiformula_sensing/rear_potentiometer/yaw"

perception:
  mask_image: "/aiformula_perception/road_detector/mask_image"
  annotated_mask_image: "/aiformula_perception/lane_line_publisher/annotated_mask_image"
  lane_lines:
    left: "/aiformula_perception/lane_line_publisher/lane_lines/left"
    right: "/aiformula_perception/lane_line_publisher/lane_lines/right"
    center: "/aiformula_perception/lane_line_publisher/lane_lines/center"

control:
  game_pad: "/aiformula_control/joy_node/joy"
  speed_command:
    game_pad: "/aiformula_control/game_pad/cmd_vel"
    handle_controller: "/aiformula_control/handle_controller/cmd_vel"
  output_can_data: "/aiformula_control/motor_controller/reference_signal"

# planning:

visualization:
  annotated_mask_image: "/aiformula_visualization/road_detector/annotated_mask_image"

