sensing:
  zed:
    left_image:
      raw: "/aiformula_sensing/zedx_image_publisher/left_image/raw"
      raw_compressed: "/aiformula_sensing/zedx_image_publisher/left_image/raw/compressed"
  input_can_data: "/aiformula_sensing/vehicle_info"
  imu: "/aiformula_sensing/vectornav/imu"
  odometry: "/aiformula_sensing/gyro_odometry/odom"

# perception:

control:
  game_pad: "/aiformula_control/joy_node/joy"
  speed_command:
    game_pad: "/aiformula_control/game_pad/cmd_vel"
    handle_controller: "/aiformula_control/handle_controller/cmd_vel"
  output_can_data: "/aiformula_control/roboteq_controller/reference_signal"

# planning:

# visualization:
