/**:
  ros__parameters:
    zedx:  # SN42356620.conf
      LEFT_CAM_FHD1200:
        size: { width: 1920, height: 1200 } # [pix]
        focal_length: { x: 738.254, y: 737.734 } # [pix]
        center_point: { x: 1000.2, y: 606.508 } # [pix]

      RIGHT_CAM_FHD1200:
        size: { width: 1920, height: 1200 } # [pix]
        focal_length: { x: 738.909, y: 738.293 } # [pix]
        center_point: { x: 994.507, y: 601.377 } # [pix]

      LEFT_CAM_FHD:
        size: { width: 1920, height: 1080 } # [pix]
        focal_length: { x: 738.254, y: 737.734 } # [pix]
        center_point: { x: 1000.2, y: 546.508 } # [pix]

      RIGHT_CAM_FHD:
        size: { width: 1920, height: 1080 } # [pix]
        focal_length: { x: 738.909, y: 738.293 } # [pix]
        center_point: { x: 994.507, y: 541.377 } # [pix]

      LEFT_CAM_SVGA:
        size: { width: 800, height: 600 } # [pix]
        focal_length: { x: 369.127, y: 368.867 } # [pix]
        center_point: { x: 500.1, y: 303.254 } # [pix]

      RIGHT_CAM_SVGA:
        size: { width: 800, height: 600 } # [pix]
        focal_length: { x: 369.4545, y: 369.1465 } # [pix]
        center_point: { x: 497.2535, y: 300.6885 } # [pix]

      LEFT_CAM_VGA:
        size: { width: 640, height: 480 } # [pix]
        focal_length: { x: 351.250000, y: 351.250000 } # [pix]
        center_point: { x: 334.250000, y: 186.250000 } # [pix]

      RIGHT_CAM_VGA:
        size: { width: 640, height: 480 } # [pix]
        focal_length: { x: 351.250000, y: 351.250000 } # [pix]
        center_point: { x: 334.250000, y: 186.250000 } # [pix]

      LEFT_DISTO:
        k1: 0.28299
        k2: 1.62744
        k3: 0.0607453
        k4: 0.290532
        k5: 1.63914
        k6: 0.148338
        p1: -0.000185121
        p2: 0.000127521

      RIGHT_DISTO:
        k1: 3.70167
        k2: 4.43118
        k3: 0.887271
        k4: 3.72003
        k5: 4.39394
        k6: 1.27063
        p1: 0.000121246
        p2: -0.000179953

      STEREO:
        Baseline: 120.005
        TY: -0.135067
        TZ: 0.287525
        CV_FHD: 0.0026372
        CV_SVGA: 0.0026372
        CV_FHD1200: 0.0026372
        RX_FHD: 0.0057774
        RX_SVGA: 0.0057774
        RX_FHD1200: 0.0057774
        RZ_FHD: 0.000490778
        RZ_SVGA: 0.000490778
        RZ_FHD1200: 0.000490778

      MISC:
        Sensor_ID: 1
