<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="zed_joint_macro"
               params="camera parent
                       x y z roll pitch yaw">
    <joint name="${camera}_joint" type="fixed">
      <parent link="${parent}_link"/>
      <child  link="${camera}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="zed_link_macro"
               params="camera
                       size_x size_y size_z roll pitch yaw">
    <xacro:property name="mesh_file" value="package://vehicle/xacro/meshes/r200.dae"/>
    <link name="${camera}_link">
      <visual>
        <origin xyz="${-size_x*0.5} ${-size_y*0.5} ${-size_z*0.5}" rpy="${roll} ${pitch} ${yaw}"/>
        <geometry>
          <mesh filename="${mesh_file}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${-size_x*0.5} ${-size_y*0.5} ${-size_z*0.5}" rpy="${roll} ${pitch} ${yaw}"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${camera}_left_joint" type="fixed">
      <parent link="${camera}_link"/>
      <child link="${camera}_left_link"/>
      <origin xyz="0.0 ${size_y*0.5} 0.0" rpy="0.0  0.0  0.0"/>
    </joint>
    <link name="${camera}_left_link"/>

    <joint name="${camera}_right_joint" type="fixed">
      <parent link="${camera}_link"/>
      <child link="${camera}_right_link"/>
      <origin xyz="0.0 ${-size_y*0.5} 0.0" rpy="0.0  0.0  0.0"/>
    </joint>
    <link name="${camera}_right_link"/>
  </xacro:macro>  
</robot>
